/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Welcome(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/static/Fox.glb");
  const { actions } = useAnimations(animations, group);
  const resize = 20
  
  return (
    <group>
      <mesh position-y={ 0 } rotation-x={ - Math.PI * 0.5 } scale={ resize }>
        <planeGeometry />
        <meshStandardMaterial color="greenyellow" />
      </mesh>
      <mesh position-y={resize*0.25} position-z={-resize*0.5} scale={ [resize,resize*0.5,resize] }>
        <planeGeometry />
        <meshStandardMaterial color="blue" />
      </mesh>
      <mesh position-y={resize*0.25}  position-z={resize*0.5} scale={ [resize,resize*0.5,resize] } rotation-x={-Math.PI}>
        <planeGeometry />
        <meshStandardMaterial color="red" />
      </mesh>
      <mesh position-y={resize*0.25}  position-x={-resize*0.5} scale={ [resize,resize*0.5,resize] } rotation-y={Math.PI*0.5}>
        <planeGeometry />
        <meshStandardMaterial color="purple" />
      </mesh>
    </group>
  );
}

useGLTF.preload("/static/Fox.glb");
